server:
  port: 8083
  
eureka:
  client:
    fetchRegistry: true
    registryWithEureka: true
    service-url:
      default-zone: http://localhost:8082/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8001
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: http://localhost:8002
          predicates:
            - Path=/product/**
        - id: operations-service
          uri: http://localhost:8003
          predicates:
            - Path=/operations/**