server:
  port: 8002
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Proyecto01BD  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8082/eureka/
